name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Haskell
      uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.8.2'
        cabal-version: '3.10'

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: dist-newstyle
        key: ${{ runner.os }}-${{ hashFiles('**/*.cabal') }}

    - name: Install tools
      run: |
        cabal update
        cabal install hlint fourmolu --overwrite-policy=always

    - name: Clean and rebuild
      run: |
        cabal clean
        cabal update
        cabal build

    - name: Run tests
      run: |
        cabal test fp-lab2-test

    - name: Lint with HLint
      run: |
        hlint .

    - name: Check formatting with fourmolu
      run: |
        find app arc tests -name "*.hs" -exec fourmolu --mode inplace {} +